# Generated by Django 3.2 on 2021-04-29 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Undefined', max_length=64)),
                ('description', models.CharField(default='No description.', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(null=True)),
                ('status', models.TextField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In progress', 'In Progress'), ('Completed', 'Completed')], default='New')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
